sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    timeout: 10s
  alioss:
    endpoint: ${ALI_OSS_ENDPOINT:}
    access-key-id: ${ALI_OSS_ACCESS_KEY_ID:}
    access-key-secret: ${ALI_OSS_ACCESS_KEY_SECRET:}
    bucket-name: ${ALI_OSS_BUCKET_NAME:}
